df <- read.csv("D:\\TEST_DSToolBox\\datasciencecoursera\\crs4-wk1\\household_power_consumption.txt",header=TRUE,sep=";")
df$datetime<- with(df, as.POSIXct(paste(Date, Time), format="%d/%m/%Y%H:%M:%S"))
df$Global_active_power <- as.numeric(df$Global_active_power)

df_filter <- subset(df,df$datetime>="2007/02/01"&df$datetime < "2007/02/03")
png(filename = "D:\\TEST_DSToolBox\\ExData_Plotting1\\Plot4.png",width = 480, height = 480, units = "px" )
par (mfrow=c(2,2))
plot(df_filter$datetime,df_filter$Global_active_power,xlab="",ylab="Global Active Power",type="l")
plot(df_filter$datetime,df_filter$Voltage,xlab="datetime",ylab="Voltage",type="l")
with(df_filter,plot(df_filter$datetime,df_filter$Sub_metering_1,type="l",main="",ylab="Energy Sub Metering",xlab=""))
lines(df_filter$datetime,df_filter$Sub_metering_2,col="red")
lines(df_filter$datetime,df_filter$Sub_metering_3,col="blue")
legend(x="topright",legend=c("sub_metering_1", "sub_metering_2", "sub_metering_3"),col=c("black","red","blue"),lty=1,lwd=2)
plot(df_filter$datetime,df_filter$Global_reactive_power,xlab="datetime",ylab="Global_rective_power",type="l")
dev.off()
